### ISSUE TITLE
Not sending messages if app is closed immediately

### ISSUE THREAD

**Issue by blmbyd** [jonfreeland/Log4Slack#14]
I  created simple ConsoleApp to test appender:
```
        static void Main(string[] args)
        {
            var message = Guid.NewGuid().ToString();

            log.Debug(message);
            log.Info(message);
            log.Warn(message);
            log.Error(message);
            log.Fatal(message);

            Console.ReadKey();
        }
```
When I comment `ReadKey` app is not sending messages.

**Comment by vforteli** [comment]
As far as I know this is by design in log4net. It is a best effort logger and if you need to be sure it has time to log everything, you should call shutdown or close before exiting
