### ISSUE TITLE
Can't get the logger to post :-(

### ISSUE THREAD

**Issue by pms1969** [jonfreeland/Log4Slack#6]
I've added log4slack to my application, and I think I've configured it correctly (added my company name and token, and changed the room/channel name, removed the icon url, and set AddAttachment and UsernameAppendLoggerName  to false. Log4Net includes the SlackAppender in the root setup.  Yet I don't seem to be able to get any log messages thru. :-(

Do you have any suggestions on how to debug this in order to figure out what is failing?

**Comment by wqweto** [comment]
I'm using something like this:
```
<log4net>
    ...
    <appender name="Services.SlackError" type="Log4Slack.SlackAppender, Log4Slack">
      <WebhookUrl value="https://hooks.slack.com/services/T0JR4LRJN/B0JR4QHUP/YourHookHere" />
      <Channel value="#YourServerName" />
      <Username value="YourBotName" />
      <IconUrl value="https://www.domain.com/ThisIsNotUsed.ico" />
      <AddAttachment value="true" />
      <AddExceptionTraceField value="true" />
      <UsernameAppendLoggerName value="true"/>
      <filter type="log4net.Filter.LevelRangeFilter">
        <levelMin value="ERROR" />
        <levelMax value="FATAL" />
      </filter>
    </appender>
    ...
    <root>
      <level value="ALL" />
      <appender-ref ref="Services.Debug" />
      <appender-ref ref="Services.Error" />
      <appender-ref ref="Services.SlackError" />
      <appender-ref ref="Services.Forward.Company1" />
      <appender-ref ref="Services.Forward.Company2" />
    </root>
</log4net>
```

**Comment by pms1969** [comment]
Thanks I'll have a look at that on my journey home, and see if I can't make it work.

Looking a your setup, I'm not sure if I've got the right webhookurl.  Is there some kind of request of a hook token?  I've got an api token I was using for a hubot.  Maybe that's my problem...

**Comment by wqweto** [comment]
Well, I just created a separate Slack team for my logs as I don't want to exhaust my main team search history on free plan (10k msgs), then for this new team configured [Incoming WebHooks](https://slack.com/apps/A0F7XDUAZ-incoming-webhooks) from slack App Directory and then in Slack added a channel for each server I'm planning on receiving messages from.

Note that a single WebHook integration can post to all channels in a Slack team. Also note that in the desktop version of Slack you can config and switch teams really easy.

**Comment by pms1969** [comment]
@wqweto Thanks for the help.  I won't be on the train for a few hours yet, but I'll be sure to try your suggestions when I am.

**Comment by jonfreeland** [comment]
Let us know, @pms1969. I should be available to help as well later today.

**Comment by pms1969** [comment]
Thanks for all the help @wqweto, and for your offer @jonfreeland.  It was the url that was wrong.  setting up the incoming webhook for my channel gave me everything that I needed, and I'm now happily posting.
