### ISSUE TITLE
Appender does not respect conversionPattern setting

### ISSUE THREAD

**Issue by greatvovan** [jonfreeland/Log4Slack#7]
I set up some message pattern (e.g. %logger: %message%newline) but I see only %message in Slack.

```
<layout type="log4net.Layout.PatternLayout">
	<conversionPattern value="%logger: %message%newline" />
</layout>
```

**Comment by jonfreeland** [comment]
Thanks for the heads up @greatvovan. I will look into this.

**Comment by greatvovan** [comment]
No, it works in latest version, sorry.
